### ISSUE TITLE
Update xmldom package (now published to npm as @xmldom/xmldom)

### ISSUE THREAD

**Issue by scottsalvaggio** [ExLibrisGroup/exl-touchnet-connector#10]
When running `npm audit`, I noticed that there are 2 moderate severity vulnerabilities, both related to the `xmldom` package.

Note that the `xmldom` package now lives [here](https://www.npmjs.com/package/@xmldom/xmldom) (`@xmldom/xmldom` instead of `xmldom`) because the current maintainers are unable to publish to the original npm library.

According to [this page](https://github.com/xmldom/xmldom/issues/271): "To get the security update, you have to switch the package you use in your `package.json`".

**Comment by scottsalvaggio** [comment]
Hi @jweisman. After pulling down commit a1f26b2, I'm getting `Error: Cannot find module 'xmldom'`.

The following changes should fix this: Pull Request #11 and this [almarestapi-node-lib Pull Request](https://github.com/jweisman/almarestapi-node-lib/pull/2).

You may also want to update the `package.json` and `package-lock.json` files inside the `exl-touchnet-connector/dependencies/nodejs` directory. Those files still reference the old `xmldom` package.

**Comment by jweisman** [comment]
Wow @scottsalvaggio - how embarrassing! Thanks for catching this. PRs merged and new almarestapi-node-lib published.

Thanks!

**Comment by scottsalvaggio** [comment]
Hi @jweisman. No problem! Thanks for merging and publishing everything so quickly. The app is running just fine now on my end.
