### ISSUE TITLE
Update json-schema package

### ISSUE THREAD

**Issue by scottsalvaggio** [ExLibrisGroup/exl-touchnet-connector#17]
When running `npm audit`, I noticed that there are 2 moderate-severity vulnerabilities, both related to the `json-schema` package.

Note that `json-schema` is a dependency of [almarestapi-lib](https://github.com/jweisman/almarestapi-node-lib). So that repository will likely need to be updated and published so you can reference the new version here.

**Comment by jweisman** [comment]
Hi @scottsalvaggio - these vulnerabilities are pretty far down the dependency tree. I ran `npm audit fix` and committed the new version. You can do the same or grab the latest version.

**Comment by scottsalvaggio** [comment]
Thanks @jweisman!
