### ISSUE TITLE
Support for paying specific fine (if there are multiple fines) or making a partial payment

### ISSUE THREAD

**Issue by scottsalvaggio** [ExLibrisGroup/exl-touchnet-connector#18]
Is there currently support for either of the following use cases?
- Specify which fine to pay (if there are multiple fines)
- Make a partial payment (rather than pay the full amount of a fine or fines)

This is our current user experience:
- Within Primo, you see all your fines, but the Pay Fine link is next to the total balance.
- When you click the Pay Fine link and are taken to the Touchnet payment page, there is only an option to pay the total balance.

If there is no way to currently do this, could you add the functionality to:
1. Allow the user to specify which fine(s) they want to pay.
2. Allow the user to edit the amount they want to pay (so they can make a partial payment).

**Comment by jweisman** [comment]
Hi @scottsalvaggio - the connector currently doesn't allow selection of which fines to pay. However, the uPay site in Touchnet can be configured to allow the user to specify / change the amount to pay. If the user pays less than the full amount, Alma will apply the payment to the relevant fines and update the remaining balance accordingly. 

Let us know if that works for you.

**Comment by scottsalvaggio** [comment]
Hi @jweisman. Thanks for your suggestion. For our dev instance, I was able to configure the Touchnet uPay site as you mentioned.

We're working with our various library stakeholders to determine how to proceed. We'll be in touch in the future once we have a better plan of what our stakeholders want.
