### ISSUE TITLE
Primo or Primo VE?

### ISSUE THREAD

**Issue by fruehanp1** [ExLibrisGroup/exl-touchnet-connector#2]
I see that the ReadMe refers to a Knowledge Center article on how one activates this within Primo VE with the _online_payment_url_ parameter, but is there an equivalent mapping table parameter in Primo Back Office?

**Comment by jweisman** [comment]
Hi @fruehanp1 - it is possible to configure a Pay Fines link in Primo (see this [blog post\(https://developers.exlibrisgroup.com/blog/integrating-alma-and-paypal-with-the-alma-rest-apis/#payfineslink)). However, this connector only knows how to extract the user name from the Primo VE JWT token, so it won't work with Primo without some additional code changes.
