### ISSUE TITLE
Update ajv package

### ISSUE THREAD

**Issue by scottsalvaggio** [ExLibrisGroup/exl-touchnet-connector#20]
Running npm audit is currently showing 2 moderate-severity vulnerabilities related to the ajv package.

Note that ajv is also a dependency of [almarestapi-lib](https://github.com/jweisman/almarestapi-node-lib). So that repository will likely need to be updated and published so you can reference the new version here.

It looks like the associated dependabot pull requests (#19 for this repo and jweisman/almarestapi-node-lib#3 for the almarestapi-lib repo) will address this issue.

**Comment by jweisman** [comment]
Updated both libraries.
