### ISSUE TITLE
Return URL Question

### ISSUE THREAD

**Issue by jweisman** [ExLibrisGroup/exl-touchnet-connector#21]
Thanks for your help with this.   That indeed was the issue.  On our local server we had to configure the firewall rule to allow outgoing traffic to port :8702   Once I did that the payments went through correctly.

There's one last piece of this though that doesn't seem to work, at least in the way I am using it.  I can open another issue here for it if you want.

I'm not getting any luck with the success page once I successfully make a payment.   When it uses the referrer as the return URL it says it can't find that page: "?touchnet/null"  According to your instructions on the README I can specify a return URL.  I have done this in the Javascript if you look at the fines landing page, but when the payment comes back from Touchnet I get the response "Cannot POST /success"   It goes to the URL http://libapps-stage-01.uit.tufts.edu:3002/success?institution=01TUN_INST&UPAY_SITE_ID=43       

Here is the URL of the fines page, with a jwt:  https://www.library.tufts.edu/hsteele/alma_touchnet_integration/index.html?&jwt=eyJraWQiOiJwcmltYVByaXZhdGVLZXktMDFUVU5fSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6IjRBRjcwRUFBOTU5QUI1QTkwMzg1MkY3NzU0OTc4NjY5LmFwcDAxLm5hMDEucHNiLmFsbWEuZGMwMS5ob3N0ZWQuZXhsaWJyaXNncm91cC5jb206MTgwMSIsImV4cCI6MTY0NDUyNTQ4OSwiaWF0IjoxNjQ0NDM5MDg5LCJ1c2VyTmFtZSI6IjQ5RTNBQjNGMDkyMEU2QjJBNjUwNkRFRTQwM0IwRkYzIiwiZGlzcGxheU5hbWUiOiJTdGVlbGUsIEhlbnJ5IiwidXNlciI6IjQ5NjMwODYzMDAwMzg1MSIsInVzZXJHcm91cCI6IlN0YWZmIiwiaW5zdGl0dXRpb24iOiIwMVRVTl9JTlNUIiwidXNlcklwIjoiMTMwLjY0LjQxLjE1OCIsImF1dGhlbnRpY2F0aW9uUHJvZmlsZSI6IkVNQUlMIiwiYXV0aGVudGljYXRpb25TeXN0ZW0iOiJBbG1hIiwibGFuZ3VhZ2UiOiJlbiIsInNhbWxTZXNzaW9uSW5kZXgiOiIiLCJzYW1sTmFtZUlkIjoiIiwib25DYW1wdXMiOiJmYWxzZSIsInNpZ25lZEluIjoidHJ1ZSIsInZpZXdJZCI6IjAxVFVOX0lOU1Q6MDFUVU4ifQ.P4afHZtlZ7Zo3bDtIuJ0TH5oKtEnIuPoxzZ6JHUw_Ewb-0x3X5NyfWwrpUF5ke4bL0NOeotEu9CxXpXAnLdnOQ

_Originally posted by @puck78 in https://github.com/ExLibrisGroup/exl-touchnet-connector/issues/12#issuecomment-1034208681_

**Comment by jweisman** [comment]
Hi @puck78- the question is where do you want the user to return to after the transaction is complete? In the [documentation](https://github.com/ExLibrisGroup/exl-touchnet-connector#return-url), it shows an option to add a `returnUrl` parameter to the query string on the link to the connector. I don't see such a parameter on the link on the [Pay Fines page](https://www.library.tufts.edu/hsteele/alma_touchnet_integration/index.html?&jwt=eyJraWQiOiJwcmltYVByaXZhdGVLZXktMDFUVU5fSU5TVCIsImFsZyI6IkVTMjU2In0.eyJpc3MiOiJQcmltYSIsImp0aSI6IjRBRjcwRUFBOTU5QUI1QTkwMzg1MkY3NzU0OTc4NjY5LmFwcDAxLm5hMDEucHNiLmFsbWEuZGMwMS5ob3N0ZWQuZXhsaWJyaXNncm91cC5jb206MTgwMSIsImV4cCI6MTY0NDUyNTQ4OSwiaWF0IjoxNjQ0NDM5MDg5LCJ1c2VyTmFtZSI6IjQ5RTNBQjNGMDkyMEU2QjJBNjUwNkRFRTQwM0IwRkYzIiwiZGlzcGxheU5hbWUiOiJTdGVlbGUsIEhlbnJ5IiwidXNlciI6IjQ5NjMwODYzMDAwMzg1MSIsInVzZXJHcm91cCI6IlN0YWZmIiwiaW5zdGl0dXRpb24iOiIwMVRVTl9JTlNUIiwidXNlcklwIjoiMTMwLjY0LjQxLjE1OCIsImF1dGhlbnRpY2F0aW9uUHJvZmlsZSI6IkVNQUlMIiwiYXV0aGVudGljYXRpb25TeXN0ZW0iOiJBbG1hIiwibGFuZ3VhZ2UiOiJlbiIsInNhbWxTZXNzaW9uSW5kZXgiOiIiLCJzYW1sTmFtZUlkIjoiIiwib25DYW1wdXMiOiJmYWxzZSIsInNpZ25lZEluIjoidHJ1ZSIsInZpZXdJZCI6IjAxVFVOX0lOU1Q6MDFUVU4ifQ.P4afHZtlZ7Zo3bDtIuJ0TH5oKtEnIuPoxzZ6JHUw_Ewb-0x3X5NyfWwrpUF5ke4bL0NOeotEu9CxXpXAnLdnOQ) you referenced above.

**Comment by HSteeleLTS** [comment]
I realized what I needed to do to make application send the success and cancel pages send to library specific pages.   It involved me understanding which parts of the Node JS app were server side vs what's being served to the client.    In the function I added that added a route for "cancel"    I added this line, which serves content to the frontend through express

    response.status(200).send(responses.goToCancel(cancelUrl));

that fucntion servers a form and a redirect just like "success"  The cancel and success URLs are coming through as URL parameters from the sending site link the user clicks on.

I think this can be closed.   Thanks!

**Comment by jweisman** [comment]
Glad to hear you worked it out! I'll go ahead and close this issue. 

If you'd like to open a pull request, we can consider how to integrate your changes into the main branch.

**Comment by HSteeleLTS** [comment]
THanks, Josh!  I will definitely submit a pull request.  There was one more piece of functionality I had to build in first, namely a postback mechanism.  This is something that exists in the non-integrated Touchnet, and like the success and cancel pages, is specified in the uPay site setting.  I have a method now in responses that handles this, by sending the success message to an institution specific postback script, that I specfiy with an additional environment variable

There is one more thing I think you may want to put in to make the application complete, namely a way to stop the application, unless you have a suggestion for doing this as the app exists now.  In packages.json you specify a start script you can invoke with npm start, but there's nothing for stop.   This would be necessary to run the application as a service.  Right now, I'm just sigkilling the app based on a PID, but obviosuly this isn't ideal.

Here's a description of ways to set up stop scripts for Node JS apps:

https://stackoverflow.com/questions/23258421/how-to-stop-app-that-node-js-express-npm-start

**Comment by jweisman** [comment]
Hi @HSteeleLTS - take a look at #16 - see if that answers your needs.
